steps:
 # - id: 'Post-deployment notification'
 #   name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
 #   entrypoint: 'bash'
 #   args:
 #     - '-c'
 #     - |
 #       gcloud scheduler jobs update http ${_COMPONENT_NAME}-job \
 #         --location ${_REGION} \
 #         --schedule="0 * * * *" \
 #         --uri="https://${_REGION}-run.googleapis.com/apis/run.googleapis.com/v1/namespaces/${PROJECT_ID}/jobs/${_COMPONENT_NAME}-${_ENV}:run" \
 #         --http-method POST \
 #         --time-zone=America/Santiago \
 #         --oauth-service-account-email ${_RUN_SERVICE_ACCOUNT_EMAIL}
  # Paso 1: Instalar dependencias
  - name: 'python:3.9'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        pip install --upgrade pip
        pip install -r requirements.txt


  # Paso 3: Construir la imagen Docker
  - id: 'Build docker image'
    name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'build'
      - '-t'
      - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_DOCKER_REPOSITORY}/${_COMPONENT_NAME}:$BUILD_ID'
      - '.'

  # Paso 4: Push de la imagen a Container Registry
  - id: 'Push docker image'
    name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_DOCKER_REPOSITORY}/${_COMPONENT_NAME}:$BUILD_ID'

  # Paso 5: Desplegar a Cloud Run Jobs
  - id: 'Deploy to Cloud Run'
    name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'jobs'
      - 'deploy'
      - '${_COMPONENT_NAME}-${_ENV}'
      - '--image'
      - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_DOCKER_REPOSITORY}/${_COMPONENT_NAME}:$BUILD_ID'
      - '--region'
      - '${_REGION}'
      - '--service-account'
      - '${_RUN_SERVICE_ACCOUNT_EMAIL}'
      - '--set-env-vars=ENV=${_ENV}'
      - '--set-env-vars=PROJECT_ID=$PROJECT_ID'
      - '--set-env-vars=FIRESTORE_PROJECT_ID=$PROJECT_ID'
      - '--set-env-vars=FIRESTORE_REGISTROS_LLAMADAS_COLLECTION=${_FIRESTORE_REGISTROS_LLAMADAS_COLLECTION}'
      - '--set-env-vars=FIRESTORE_AUDIOS_STATUS_COLLECTION=${_FIRESTORE_AUDIOS_STATUS_COLLECTION}'
      - '--set-env-vars=FIRESTORE_DATABASE=${_FIRESTORE_DATABASE}'
      - '--set-env-vars=GCS_BUCKET_NAME=${_GCS_BUCKET_NAME}'
      - '--set-env-vars=GCS_PROJECT_ID=$PROJECT_ID'
      - '--set-env-vars=GCS_AUDIO_PREFIX=${_GCS_AUDIO_PREFIX}'
      - '--set-env-vars=SFTP_HOST=${_SFTP_HOST}'
      - '--set-env-vars=SFTP_PORT=${_SFTP_PORT}'
      - '--set-env-vars=SFTP_USERNAME=${_SFTP_USERNAME}'
      - '--set-env-vars=SFTP_PASSWORD=${_SFTP_PASSWORD}'
      - '--set-env-vars=SFTP_UPLOAD_PATH=${_SFTP_UPLOAD_PATH}'
      - '--set-env-vars=PIPE_CONVERT_TO_WAV=${_PIPE_CONVERT_TO_WAV}'
      - '--set-env-vars=AGENT_ID=${_AGENT_ID}'

# Configuraciones adicionales
options:
  logging: CLOUD_LOGGING_ONLY

# Timeout del build
timeout: '1200s'
